from fastapi import APIRouter, HTTPException
from api.models import QueryRequest, QueryResponse, ErrorResponse
from graph import run_rag_query
import time

router = APIRouter(prefix="/query", tags=["query"])

@router.post("/", response_model=QueryResponse)
async def query_rag(request: QueryRequest):

    start_time = time.time()

    try:

        final_state = run_rag_query(request.question)

        elapsed_time = round(time.time() - start_time, 3)

        resolved_answer = (
            final_state.get("final_answer")
            or final_state.get("answer")
            or "An issue occurred: No response text was generated by the pipeline. (Low Quality)"
        )

        resolved_quality = final_state.get("retrieval_quality") or "unknown"
        resolved_confidence = float(final_state.get("confidence_score", 0.0))

        raw_chunks = final_state.get("retrieved_chunks", [])
        sources = []

        if request.include_sources and raw_chunks:
            for idx, c in enumerate(raw_chunks):
                sources.append({
                    "source": c.get("source", "unknown_origin"),
                    "chunk_index": c.get("chunk_index", idx),
                    "score": float(c.get("score", 0.0))
                })

        response = QueryResponse(
            answer=resolved_answer,
            confidence_score=resolved_confidence,
            retrieval_quality=resolved_quality,
            sources=sources if request.include_sources else None,
            processing_time=max(0.0, elapsed_time),
        )

        return response

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
